[package]
name = "xee-xpath-lexer"
version = "0.1.4"
edition.workspace = true
publish.workspace = true
authors.workspace = true
keywords = ["xml", "xpath"]
license.workspace = true
description = "XPath lexer"
repository.workspace = true
readme = "README.md"
homepage.workspace = true

[features]
serde = ["dep:serde", "ibig/serde"]

[dependencies]
logos = "0.15.0"
ibig = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
itertools = "0.14.0"

[dev-dependencies]
# we want to depend on serde feature during tests
xee-xpath-lexer = { path = ".", features = ["serde"] }
insta = { workspace = true, features = ["yaml", "glob"] }
rust_decimal_macros = { workspace = true }
ron = { workspace = true }
