[package]
name = "xee-ir"
version = "0.1.5"
edition.workspace = true
publish.workspace = true
authors.workspace = true
keywords = ["xml", "xpath", "xslt"]
categories = ["text-processing", "compilers"]
license.workspace = true
description = "Xee intermediate representation and compilation to bytecode"
repository.workspace = true
readme = "README.md"
homepage.workspace = true

[dependencies]
xee-xpath-ast = { workspace = true }
xee-schema-type = { workspace = true }
xee-interpreter = { workspace = true }
ahash = { workspace = true }
ordered-float = { workspace = true }
rust_decimal = { workspace = true }
ibig = { workspace = true }
xot = { workspace = true }


[dev-dependencies]
insta = { workspace = true, features = ["yaml", "glob"] }
