[package]
name = "xee-xpath-type"
version = "0.1.4"
edition.workspace = true
publish.workspace = true
authors.workspace = true
keywords = ["xml", "xpath"]
license.workspace = true
description = "XPath type information"
repository.workspace = true
readme = "README.md"
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serde = ["dep:serde", "xot/serde"]

[dependencies]
xee-schema-type = { workspace = true }
xee-name = { workspace = true }
xot = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
