[package]
name = "xee-xslt-ast"
version = "0.1.6"
edition.workspace = true
publish.workspace = true
authors.workspace = true
keywords = ["xml", "xslt"]
license.workspace = true
description = "XSLT parser and AST implementation"
repository.workspace = true
readme = "README.md"
homepage.workspace = true

[features]
serde = [
    "dep:serde",
    "xee-xpath-ast/serde",
    "xee-xpath-compiler/serde",
    "xot/serde",
]

[dependencies]
xee-xpath-ast = { workspace = true }
xee-xpath-compiler = { workspace = true }
xee-name = { workspace = true }
ahash = { workspace = true }
thiserror = { workspace = true }
xot = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
strum = { workspace = true }
blanket = { workspace = true }
rust_decimal = { workspace = true }

[dev-dependencies]
# we want to depend on serde feature during tests
xee-xslt-ast = { path = ".", features = ["serde"] }
insta = { workspace = true, features = ["ron", "glob"] }
xot = { workspace = true, features = ["proptest"] }
ron = { workspace = true }
