[package]
name = "xee-name"
version = "0.1.5"
edition.workspace = true
publish.workspace = true
authors.workspace = true
keywords = ["xml", "xpath"]
license.workspace = true
description = "Xee XML namespace support"
repository.workspace = true
readme = "README.md"
homepage.workspace = true

[features]
serde = ["dep:serde"]

[dependencies]
ahash = { workspace = true }
xot = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }
