[package]
name = "xee-xpath-ast"
version = "0.1.4"
edition.workspace = true
publish.workspace = true
authors.workspace = true
keywords = ["xml", "xpath"]
license.workspace = true
description = "XPath parser and AST implementation"
repository.workspace = true
readme = "README.md"
homepage.workspace = true

[features]
serde = [
    "dep:serde",
    "ibig/serde",
    "ordered-float/serde",
    "chumsky/serde",
    "xee-schema-type/serde",
    "xee-xpath-type/serde",
    "xee-name/serde",
    "xot/serde",
]

[dependencies]
xee-schema-type = { workspace = true }
xee-name = { workspace = true }
xee-xpath-type = { workspace = true }
xee-xpath-lexer = { workspace = true }
ahash = { workspace = true }
chumsky = { workspace = true }
blanket = { workspace = true }
ordered-float = { workspace = true }
ibig = { workspace = true }
rust_decimal = { workspace = true }
thiserror = { workspace = true }
xot = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }


[dev-dependencies]
# we want to depend on serde feature during tests
xee-xpath-ast = { path = ".", features = ["serde"] }
insta = { workspace = true, features = ["ron", "glob"] }
xot = { workspace = true, features = ["proptest"] }
rust_decimal_macros = { workspace = true }
ron = { workspace = true }
