[package]
name = "xee-xpath-load"
version = "0.2.0"
edition.workspace = true
publish.workspace = true
authors.workspace = true
keywords = ["xml", "xpath"]
license.workspace = true
description = "Load XML into structs using XPath"
repository.workspace = true
readme = "README.md"
homepage.workspace = true


[dependencies]
xee-xpath-compiler = { workspace = true }
xee-xpath = { workspace = true }
thiserror = { workspace = true }
xot = { workspace = true }
ibig = { workspace = true }
rust_decimal = { workspace = true }
anyhow = { workspace = true }
iri-string = { workspace = true }

[dev-dependencies]
insta = { workspace = true, features = ["yaml", "glob"] }
