[package]
name = "xee"
version = "0.1.6"
edition.workspace = true
publish.workspace = true
authors.workspace = true
keywords = ["xml", "xpath"]
license.workspace = true
description = "Xee CLI. Swiss Army knife for XML. XPath and XSLT"
repository.workspace = true
readme = "README.md"
homepage.workspace = true

[dependencies]
xee-xpath = { workspace = true }
xee-xslt-compiler = { workspace = true }
xee-interpreter = { workspace = true }
xot = { workspace = true }
clap = { workspace = true, features = ["derive", "cargo"] }
ariadne = "0.5.1"
anyhow.workspace = true
regex = { workspace = true }
rustyline = "15.0.0"
ahash = { workspace = true }

[dev-dependencies]
