[package]
name = "xee-schema-type"
version = "0.1.4"
edition.workspace = true
publish.workspace = true
authors.workspace = true
keywords = ["xml", "xpath"]
license.workspace = true
description = "XML Schema type information"
repository.workspace = true
readme = "README.md"
homepage.workspace = true

[dependencies]
ahash = { workspace = true }
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
insta = { workspace = true, features = ["yaml", "glob"] }

[features]
serde = ["dep:serde"]
